baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "English with Chris - Native Speaker in Budapest"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  google_tag_manager_id = ""
  favicon = "favicon-32x32.svg"

  [params.homepage]
    sticky_header = true
    show_contact_box = true
    show_services_button = true

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "English with Chris - Native Speaker in Budapest"

  [params.fonts]
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#1E88E5"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_creator = ""
    meta_twitter_site = ""
    meta_og_image = ""

  [params.services]
    summary_truncate = 120

  [params.team]
    summary_large_truncate = 120

  [params.footer]
    copyright_text = '© 2024 English with Chris. All rights reserved.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
